spring:
  application:
    name: xiaoyu-search
  cloud:
    nacos:
      discovery:
        register-enabled: true

server:
  port: 9081

# Dubbo Configuration
dubbo:
  application:
    name: xiaoyu-search
  protocol:
    name: dubbo
    port: 20890
  registry:
    address: nacos://127.0.0.1:8848
  scan:
    base-packages: com.xiaoyu.search

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always

logging:
  level:
    com.alibaba.cloud.nacos: DEBUG
    com.alibaba.nacos: DEBUG
    org.springframework.cloud: DEBUG
