server:
  port: 8781

# Dubbo Configuration
dubbo:
  application:
    name: xiaoyu-product
  protocol:
    name: dubbo
    port: 20884
  registry:
    address: nacos://127.0.0.1:8848
  scan:
    base-packages: com.xiaoyu.product

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always

logging:
  level:
    com.alibaba.cloud.nacos: DEBUG
    com.alibaba.nacos: DEBUG
    org.springframework.cloud: DEBUG
